#ifndef def_LingueDefault_h_included
#define def_LingueDefault_h_included
#ifdef defLocalMain_EsportaLingue
	unsigned char ucStringhe20char_default[300][21]={
#else
	code unsigned char *ucStringhe20char_default[]={
#endif
	"Posizione" ,
	"PEZZI DA PRODURRE",
	"Valore ohmico",
	"Descrizione",
	"Dati lavorazione",
	"   Lista lavori   ",
	" Inserisci lavoro ",
	"LAVORAZIONE MANUALE",
	"L  ",
	"L+R",
	"Ohm/m filo 1",
	"Ohm/m filo 2",
	"Ohm/m filo 3" ,
	"Res. spec. fili",
	"Filo",
	"diametro filo",
	"Lega",
	"diametro mandrino",
	"numero di fili",
	"tolleranza",
	"Seleziona codice",
	"Aggiungi Pezzi",
	"LOTTO" ,
	"M",
	"R1",
	"R2",
	"CUT!",
	"SALVA",
	"LOCKD",
	"LOCKED",
	"UNLCK",
	"TARAT",
	"SI",
	"NO",
	"MENU PRINCIPALE",
	"LOTTI DI PRODUZIONE" ,
	"CONTROLLO PRODUZIONE",
	"ARCHIVIO PRODOTTI",
	"UTILITA'          ",
	"PARAMETRI MACCHINA",
	"TARATURA STRUMENTI",
	"TARATURE          ",
	"Funzionamento       ",
	"Numero fili         ",
	"Regolaz. velocita'  ",
	"Cambio automatico   ",
	"Impulsi/giro encoder",
	"Sviluppo Ruota Mis. ",
	"Unita' di Misura    ",
	"Velocita' Mandrino  ",
	"Velocita' Ruota Co.1",
	"Velocita' Ruota Co.2",
	"Pz. prima Fine      ",
	"Spegnimento Lampada ",
	"Quota taglio basso  ",
	"Quota taglio alto   ",
	"Durata Min. Allarme ",
	"DFilo Esc. Interruz.",
	"% Misura Scarta     ",
	"N. Misure Scarte    ",
	"FS Ass. Ruote Contr.",
	"Lingua              ",
	"Versione CNC        ",
	"Versione display lcd",
	"Quinta portata      ",
	"PEZZI PRODOTTI      ",
	"N. spire pretaglio",
	"Diametro coltello ",
	"Diametro ruota 1  ",
	"Diametro ruota 2  ",
	"Pos riposo taglio ",
	"   Altri parametri  ",
	"  TOLLERANZE FILO   ",
	"Tolleranza",
	"Tolleranza res. filo",
	"INGRESSI ANALOGICI",
	"USCITE ANALOGICHE ",
	"INGRESSI DIGITALI",
	"USCITE DIGITALI  ",
	"INGRESSI ENCODER " ,
	"Memorizzo setup?",
	"Misura manuale",
	"Misura dinamica",
	"  Seleziona portata ",
	"Portata manuale",
	"Portata dinamica",
	"ABILITA TARATURA R1 ",
	"ABILITA TARATURA R2 ",
	"LOG PRODUZIONE      ",
	"SALVA PARAMETRI     ",
	"DATA/ORA            ",
	"CARICA PAR. MACCHINA",
	"CARICA CODICI PROD. ",
	"CARICA LINGUA CUSTOM",
	"CNC SERIAL NUMBER   ",
	"RESET CODICI PROD.  ",
	"CALIBRA LCD         ",
	"CAMBIO BOCCOLA ",
	"START+",
	"CALIBRA TAGLIO",
	"CONTROLLO TAGLIO",
	"OHM SPIRALE",
	"Cut gain",
	"Cut dac value",
	"Cut Pos Tolerance",
	"Cut Position",
	"Slow dac Cut",
	"Non cancellare",
	"codice attivo",
	"o lotto attivo",
	"Contrasto LCD",
	"Spire di Pretaglio  ",
	"Tabella Toll. Filo  ",
	"Diam. Lama di Taglio",
	"Diam. Ruota Contra 1",
	"Diam. Ruota Contra 2",
	"Calibra Taglio",
	"      ALLARME!      ",
	"MISURA>Massimo",
	"misura<Minimo",
	"CONTATI",
	"ATTESI",
	"MASSIMO",
	"Lunghezza    "  ,
	"Misura Ohmica"  ,
	"mm"			,	   
	"inch",
	"Italiano",
	"English",
	"Custom",
	"Potenziometri",
	"Encoder",
	"Disabilitato",
	"Abilitato",
	"FINECORSA",
	"POTENZIOMETRO",
	"Filo Aggrovigliato",
	"Fault Freni 2",
	"Fault Ruota Cont. 1",
	"Fault Ruota Cont. 2",
	"Interruzione Filo 1",
	"Interruzione Filo 2",
	"Fault Mandrino",
	"Salto Misura Ohmica",
	"Tempo Misura Insuf.",
	"Filo Fuori Toll.",
	"Misura Fuori Portata",
	"Fault Taglio",
	"Errore disco USB",
	"Errore SD card",
	"Errore i2c bus",
	"Fault Misura Temp.",
	"PASSWORD",
	"Conferma password",
	"Password OK",
	"Password errata",
	"Up",
	"Dn",
	"Esc",
	"CANCELLA",
	"CANCELLA CODICE",
	" VEDI ",
	"PARAMETRI CODICE",
	"FATTORE CORREZIONE",
	"VEL. PRODUZIONE",
	"QUOTA PRETAGLIO",
	"LISTA COMPLETA",
	"Ok",
	"None",
	"Imp/Giro",
	"mm/Giro",
	"inch/Giro",
	"Rpm",
	"mt/min",
	"ft/min" ,
	"A",
	"mm",
	"inch",
	"inch-feet",
	"N.",
	"Ohm",
	"ohm/mt",
	"ohm/feet",
	"%",
	"Secondi",
	"Secondi/1000",
	"Volt" ,
	"Secondi/100",
	"OHM SPIRALE" , 
	"Impostato"  ,
	"Misurato"  ,
	"CANCELLA"  ,
	"RIPRISTINO%3i%% %c",
	"CARICA CODICI PROD. ",
	"RIPRISTINO OK  ",
	"ERRORE: %i",
	"RIAVVIO...",
	"CANCELLA CODICI PROD",
	"LOADING %c",
	"CARICO LINGUA DA USB",
	"CARICO OK   ",
	"RIPRISTINO%c",
	"RIPRISTINO PARAMETRI",
	"RIPRISTINO   OK",
	"Salvataggio...",
	"Inizio salvataggio",
	"Salvataggio OK",
	"ESEGUI  SALVATAGGIO ",
	"FILO AGGROV. ",
	"Non usato    ",
	"DRV TAGLIO KO",
	"COLTELLO SU  ",
	"Non usato    ",
	"Non usato    ",
	"MISURA ATTIVA",
	"Non usato    ",
	"START        ",
	"STOP         ",
	"START OHMTEST",
	"INTER. FILO 1",
	"INTER. FILO 2",
	"MANDRINO  KO",
	"RUOTA CONT1 KO",
	"RUOTA CONT2 KO",
	"GAMMA 0      ",
	"GAMMA 1      ",
	"GAMMA 2      ",
	"ATTIVA OHMMAN",
	"ATTIVA MOTORI",
	"TAGLIO       ",
	"PRETAGLIO    ",
	"LAMP. GIALLA ",
	"Non usato    ",
	"BANDELLA     ",
	"LAMP. ROSSA  ",
	"Non usato    ",
	"Non usato    ",
	"Non usato    ",
	"Non usato    ",
	"Non usato    ",
	"ELENCO PRODUZIONE",
	"CANCELLA LISTA JOB",
	"LISTA JOB PIENA!",
	"AGGIUNGI",
	"TEMPO SCARICO BAND. ",
	"RITARDO SCARICO BAND",
	"NF    TOLL   MODO   ",
	"RESET MEMORIA RAM   ",
	"MISURA OK",
	"VERSIONE FPGA",
	"ETHERNET MAC ADDR.",
	"TRASFERIMENTO DATI",
	"RICEZIONE DATI?",
	"Lampada allarmi",
    	"Separatore",
	"Offset Separatore",
	"Posizione discesa",
	"Posizione risalita",
	"Setup Separatore",	  // ricetta del distanziatore
	"Non presente",				// distanziatore non presente
	"Pneumatico",				// distanziatore pneumatico
	"Lama di taglio",			// come distanziatore si usa il coltello
	"TEMPO PRESEPARAZIONE",			// tempo impiegato dal distanziatore a scendere da posizione alta a posizione di distanziazione
	"SEPARATORE",			    // " spacer dn " string: indica il comando di discesa spaziatore
	"POSIZIONE:",			    // nel menu di impostazione dei parametri di distanziazione; indica l'indice della distanziazione corrente: 1.,2,...,20
	"spire",			  // nel menu di impostazione dei parametri di distanziazione; indica l'unit� di misura del numero di spire (spire/coils)	
	"Compensazione Temp.",  // temperature compensation [enabled/disabled]
	"Sens.temp.sconnesso",  // temperature compensation alarm: probe open
	"Temp. fuori scala-",  // temperature compensation alarm: probe underrange
	"Temp. fuori scala+",  // temperature compensation alarm: probe overrange
	"Timeout lettura",  // temperature compensation alarm: measure timeout
	"Temp.Comp",  // use temperature compensation 
	"Coeff.Temperatura",  // temperature coefficient [10-6/�C]
	"Std a 20*C",  // valore standard misurato @ 20�C
	"CoefT",  // fattore di temperatura: max 5 char
	
	"Par.Comp.Temp.", // title of window for temperature compensation parameters
	"T1",				// short label (max 5 chars) for 1st calibration point, temperature value 1
	"K1",				// short label (max 5 chars) for 1st calibration point, coefficient K value 1
	"T2",				// short label (max 5 chars) for 2nd calibration point, temperature value 2
	"K2",				// short label (max 5 chars) for 2nd calibration point, coefficient K value 2
	"alfa",				// short label (max 5 chars) for alfa factor used in formula R=R0*(1+alfa*(t-20�C))
	"Temperatura",				// title of window where temperature calibration points are input
	"Coeff. K",				// title of window where coefficients K calibration points are input
	"Alfa",				// title of window where alfa is input
	"Avvio comp.temp",				// message shown when temperature compensation is warming up
	"Modo",				// modo di lavoro (L o L+R)
	"RETTIFICA MANDRINO",		// rettifica mandrino
	"RUN",	// grinding running
	"STOP",	// grinding NOT running
	"STOP per fermare",	// grinding running help
	"START per iniziare",	// grinding NOT running help
	"Azzero pezzi ?",	// azzero pezzi gia' prodotti?
	"err. velocita' filo",	// errore nella velocità della ruota di contrasto: filo aggrovigliato?
		
};

#ifdef defLocalMain_EsportaLingue
	unsigned char ucStringhe40char_default[300][41]={
#else
	code unsigned char *ucStringhe40char_default[]={
#endif
	" POS  NUM PEZZI   OHM           MODO    ",
	"TEMPO RESIDUO OHM SPIRALE  NUMERO PEZZI ",
	"mt/min    RPM        ASSORB1    ASSORB2 ",
	"RPM            PRETAGLIO                ",
	"RPM            PRETAGLIO      OHM/M     ",
	"RPM            PRETAGLIO      OHM       ",
	"encoder                                 ",
	"ch#   Volt           ch#   Volt",
	" D.FILO       LEGA    MANDRINO   NF TOLL",
	"Filo per lavoro attuale",
	"Filo per tutti i lavori",
	"INNER BOX TEMPERATURE & RTC STATUS",
	"RPM              SEPARATORE             ",
	"TEMPO PRE-SEPARAZ.  CORREZIONE NUM.SPIRE",	
};



#ifdef defLocalMain_EsportaLingue
	unsigned char ucStringhe20char_english[300][21]={
#else
	code unsigned char *ucStringhe20char_english[]={
#endif
	"Position"				,
	"JOB NUM PCS"			,
	"Ohm value",
	"Description",
	"Job data",
	"     Job list     ",
	"    JOB INSERT    ",
	"MANUAL JOB",
	"L  ",
	"L+R",
	"Wire 1 Ohm/mt",
	"Wire 2 Ohm/mt",
	"Wire 3 Ohm/mt",
	"OHM/MT WIRES",
	"Wire",
	" wire diameter",
	"Alloy",
	"spindle diameter ",
	"num of wires  ",
	"tolerance ",
	"   Code Select   ",
	"Add pcs",
	"JOB",
	"S",
	"W1",
	"W2",
	"CUT!",
	"SAVE ",
	"LOCKD",
	"LOCKED",
	"UNLCK",
	"CALIB",
	"YES",
	"NO",
	"MAIN MENU",
	"JOB LIST          ",
	"PRODUCTION        ",
	"PRODUCT CODES     ",
	"UTILITIES         ",
	"MACHINE PARAMETERS",
	"MEASURE CALIBRATION ",
	"CALIBRATIONS        ",
	"Work Mode selection ",
	"Max wires to use    ",
	"Speed adjust with   ",
	"Automatic job change",
	"Encoder Pulses/rev  ",
	"Meas wheel circum.  ",
	"Measure unit        ",
	"Spindle Max speed   ",
	"Wheel 1 Max speed   ",
	"Wheel 2 Max speed   ",
	"Pcs before end      ",
	"Lamp off            ",
	"Cut Low  Position   ",
	"Cut High Position   ",
	"Min. Alarm duration ",
	"DWire Intrptn Excld.",
	"% Reject Measurement",
	"N.Reject Measurement",
	"E.S.Loading P. Wheel",
	"Language            ",
	"CNC Firmware Version",
	"LCD Firmware Version",
	"Fifth measure  range",
	"  PCS DONE        ",
	"Precut Coils",
	"Knife diam. ",
	"Wheel 1 diam.",
	"Wheel 2 diam.",
	"Cut reste position",
	"  Other parameters  ",
	"  TOLERANCE  TABLE  ",
	"Tolerance",
	"Wire res. Tolerance ",
	"ANALOG INPUTS       ",
	"ANALOG OUTPUTS      ",
	"DIGITAL INPUTS      ",
	"DIGITAL OUTPUTS     ",
	"ENCODER INPUTS      ",
	"Store setup?",
	"Manual  Measure",
	"Dynamic Measure",
	"Range select ",
	"Manual  range",
	"Dynamic range",
	"Enable calibrat. R1 ",
	"Enable calibrat. R2 ",
	"PRODUCTION LOG      ",
	"PARAMETERS SAVE     ",
	"DATE AND TIME       ",
	"LOAD MACHINE PARAMS ",
	"LOAD PRODUCT CODES  ",
	"LOAD CUSTOM LANGUAGE",
	"CNC SERIAL NUMBER   ",
	"RESET PRODUCT CODES ",
	"LCD CALIBRATION     ",
	"BUSH CHANGE",
	"START+",
	"CUT CALIBRATION",
	"CUT CONTROL",
	"COIL OHM",
	"Cut gain",
	"Cut dac value",
	"Cut Pos Tolerance",
	"Cut Position",
	"Slow dac Cut",
	"Cannot erase",
	"active code",
	"or active job",
	"LCD contrast",
	"Precut Coils    ",
	"Tolerance Table ",
	"Knife Diameter  ",
	"Wheel 1 Diameter",
	"Wheel 2 Diameter",
	"Cut Calibrate ",
	"       ALARM!       ",
	"MEASURED>Maximum",
	"measured<Minimum",
	"COUNTED",
	"WAITING",
	"MAXIMUM",
	"With length",
	"With ohm   ",
	"mm",
	"inch",
	"Italiano",
	"English",
	"Custom",
	"Potentiometers",
	"Encoder",
	"Disabled",
	"Enabled",
	"SWITCH",
	"POTENTIOMETER",
	"Bunched Wire",
	"Fault freni 2",
	"P. Wheel 1 Fault",
	"P. Wheel 2 Fault",
	"Interruption Wire 1",
	"Interruption Wire 2",
	"Mandrel Fault",
	"Skip Ohmic Measure.",
	"Insuf. Measure.Time",
	"Wire Out of Tol.",
	"Measure Out Range",
	"Knife Motor Fault",
	"USB disk error",
	"SD card error",
	"I2C bus error",
	"Temp. Measure Fault",
	"PASSWORD",
	"Confirm password",
	"Password OK",
	"Mistyped Password",
	"Up",
	"Dn",
	"Esc",
	"DELETE",
	"  CODE DELETE  ",
	"VIEW",
	"CODE PARAMETERS VIEW",
	"CORRECTION FACTOR",
	"JOB SPEED",
	"PRECUT  QUOTE",
	"  LIST ALL   ",
	"Ok",
	"None",
	"Imp/Rev",
	"mm/Rev",
	"inch/Rev",
	"Rpm",
	"mt/min",
	"ft/min",
	"A",
	"mm",
	"inch",
	"inch-feet",
	"N.",
	"OHM",
	"ohm/mt",
	"ohm/feet",
	"%",
	"Seconds",
	"Seconds/1000",
	"Volt",
	"Seconds/100",
	"Coil Ohm",
	"Set value",
	"Measured",
	"CLEAR",
	"RESTORING %3i%% %c",
	"   RESTORE CODES    ",
	"Restore ends OK",
	"Error: %i",
	"REBOOT...",
	"CLEAR ALL PROD.CODES",
	"LOADING %c",
	"    LOAD LANGUAGE   ",
	"Load ends OK",
	"RESTORING %c",
	"   RESTORE PARAMS   ",
	"Restore ends OK",
	"Saving... ",
	"Init save... ",
	"Save ends OK",
	"       Do save      ",
	"Bunched  Wire"	,
	"Not used     "	,
	"Knife   Fault"	,
	"Knife high   " ,
	"Not used     "	,
	"Not used     "	,
	"Measure valid"	,
	"Not used     "	,
	"START        "	,
	"STOP         "	,
	"START OhmTest"	,
	"Wire 1 break "	,
	"Wire 2 break "	,
	"Spindle fault"	,
	"Wheel 1 fault"	,
	"Wheel 2 fault"	,
	"Range 0      "	,
	"Range 1      "	,
	"Range 2      "	,
	"Ena  Ohm Test" ,
	"Enable Motors"	,
	"Enable Cut   "	,
	"Enable Precut"	,
	"Yellow Lamp  "	,
	"Not used     "	,
	"HOPPER       "	,
	"Red Lamp     "	,
	"Not used     "	,
	"Not used     "	,
	"Not used     "	,
	"Not used     "	,
	"Not used     " ,
	"PRODUCT LIST",
	"JOB LIST DELETE",
	"JOB LIST FULL!",
	"ADD NEW",
	"HOPPER UNLOAD TIME",
	"HOPPER DELAY  TIME",
	"WN    TOLL   MODE   ",
	"RAM MEMORY CLEAR    ",
	"MEASURE OK",
	"FPGA VERSION",
	"ETHERNET MAC ADDR.",
	"DATA TRANSFER",
	"DATA RECEIVE?",
	"Alarms lamp",
	"Separator",
	"Separator offset",
	"Downward Position",	// Posizione discesa. 
	"Upward Position",		// Posizione di risalita. 
	"Separator setup",			// ricetta del distanziatore
	"Not present",			// distanziatore non presente
	"Pneumatic",			// distanziatore pneumatico
	"Cutting knife",		// come distanziatore si usa il coltello
	"Separ.adv.time",			// tempo impiegato dal distanziatore a scendere da posizione alta a posizione di distanziazione
	"SEPARATOR DN",			// " spacer dn " string: indica il comando di discesa spaziatore
	"POSITION:",			  // nel menu di impostazione dei parametri di distanziazione; indica l'indice della distanziazione corrente: 1.,2,...,20
	"coils",			  // nel menu di impostazione dei parametri di distanziazione; indica l'unit� di misura del numero di spire (spire/coils)
	"Temperature compens.",  // temperature compensation [enabled/disabled]
	"Probe open",  // temperature compensation alarm: probe open
	"Probe underrange",  // temperature compensation alarm: probe underrange
	"Probe overrange",  // temperature compensation alarm: probe overrange
	"Read timeout",  // temperature compensation alarm: measure timeout
	"Temp.Comp",  // use temperature compensation 
	"Temperature Coeff.",  // temperature coefficient
	"Std @ 20*C",  // valore standard misurato @ 20�C
	"TCoef",  // fattore di temperatura: max 5 char
	
	"Temp.Comp.Pars", // title of window for temperature compensation parameters
	"T1",				// short label (max 5 chars) for 1st calibration point, temperature value 1
	"K1",				// short label (max 5 chars) for 1st calibration point, coefficient K value 1
	"T2",				// short label (max 5 chars) for 2nd calibration point, temperature value 2
	"K2",				// short label (max 5 chars) for 2nd calibration point, coefficient K value 2
	"alfa",				// short label (max 5 chars) for alfa factor used in formula R=R0*(1+alfa*(t-20�C))
	"Temperature value",				// title of window where temperature calibration points are input
	"Coeff. K value",				// title of window where coefficients K calibration points are input
	"Alfa value",				// title of window where alfa is input
	"Temp.comp.warmup",				// message shown when temperature compensation is warming up
	"Work Mode",				// modo di lavoro (L o L+R)
	"SPINDLE GRINDING",		// rettifica mandrino
	"RUN",	// grinding running
	"STOP",	// grinding NOT running
	"Press STOP to halt",	// grinding running help
	"Press START to begin",	// grinding NOT running help
	"Reset num pieces?" // reset num of pieces made?
	"wire speed error",	// errore nella velocità della ruota di contrasto: filo aggrovigliato?
};



//code unsigned char ucStringhe40char_english[10][41]={
#ifdef defLocalMain_EsportaLingue
	unsigned char ucStringhe40char_english[300][41]={
#else
	code unsigned char *ucStringhe40char_english[]={
#endif
	" POS  NUM PCS     COIL OHM    WORK MODE ",
	"RESIDUAL TIME  COIL OHM    TOTAL JOB PCS",
	"Mt/MIN    RPM        CURRENT1  CURRENT2 ",
	"    RPM     ADJ PRECUT                  ",
	"    RPM     ADJ PRECUT        OHM/MT    ",
	"    RPM     ADJ PRECUT         OHM      ",
	"encoder                                 ",
	"ch#   Volt           ch#   Volt",
	"WIRE-DIAMETER  ALLOY  SPINDLE    WN TOLR",
	"Wire meters for current Job",
	"Wire meters for all Jobs   ",
	"INNER BOX TEMPERATURE & RTC STATUS",
	"    RPM     ADJ SEPARATOR               ",
	"SEPARATOR ADV. TIME  OFFSET COILS NUM.  ",
};

#endif //#ifndef def_LingueDefault_h_included
